overwrite: true
schema:
  - 'https://devgateway.gardenoflove.ir/identityresourceschema'

generates:
  src/types/serverTypes.ts:
    plugins:
      - typescript
    config:
      useTypeImports: true
  src/:
    preset: near-operation-file
    documents:
      - src/graphql/idr/queries/*.gql
      - src/graphql/idr/mutations/*.gql
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types/serverTypes.ts
      importTypesNamespace: ServerTypes
    plugins:
      - typescript-operations
      - typescript-rtk-query:
          importBaseApiFrom: 'core/client/baseApi/idr'
    config:
      addDocBlocks: false
      exportFragmentSpreadSubTypes: true
      exportHooks: true
      skipTypename: true
      useTypeImports: true
