overwrite: true
schema: 
  - 'https://devgateway.gardenoflove.ir/identityresourceschema'
  - 'https://devgateway.gardenoflove.ir/cmsschema'
  - 'https://devgateway.gardenoflove.ir/postserverschema'
generates:
  ./src/types/serverTypes.ts:
    plugins:
      - typescript